---
- name: Check if global config username is set
  command: git config --global --get user.name
  register: git_config_username
  failed_when: false
  changed_when: false

- name: Check if global config email is set
  command: git config --global --get user.email
  register: git_config_email
  failed_when: false
  changed_when: false

- name: Set the global config username
  command: git config --global user.name "{{ ar_git_repo_username }}"
  when: git_config_username.rc != 0

- name: Set the global config username
  command: git config --global user.email "{{ ar_git_repo_email }}"
  when: git_config_email.rc != 0

- name: "Assert required vars are present"
  assert:
    that: ar_git_repo_assertions

- name: Check if git status has changed
  shell: cd {{ ar_git_repo_dest }} && git status --porcelain {{ ar_git_repo_subdir }} | wc -l
  register: git_status
  changed_when: false

- name: Add any additional or updated generated files to git
  shell: cd {{ ar_git_repo_dest }} && git reset HEAD && git add {{ ar_git_repo_subdir }}
  when: git_status.stdout != "0"

- name: Generate comment (tower)
  set_fact:
    _ar_git_repo_comment: "Automated update to env data issued by {{ tower_user_name }}/({{ tower_user_email }}) as of {{ ansible_date_time.date }} {{ ansible_date_time.time }}
{{ ar_git_repo_commit_comment }}"
  when: tower_user_name is defined

- name: Generate comment (not tower)
  set_fact:
    _ar_git_repo_comment: "Automated update to env data issued by {{ ansible_user }} as of {{ ansible_date_time.date }} {{ ansible_date_time.time }}
{{ ar_git_repo_commit_comment }}"
  when: tower_user_name is not defined

- name: Commit changes to git repo {{ ar_git_repo_url }} from {{ ar_git_repo_dest }}
  shell: cd {{ ar_git_repo_dest }} && git commit -m "{{ _ar_git_repo_comment }}"
  when: git_status.stdout != "0"

- name: Ensure ssh key is present
  include_tasks: ssh-key-available.yml

- name: Push changes to git repo
  shell: |
    cd {{ ar_git_repo_dest }} && \
    git push
  when: git_status.stdout != "0"

- name: Ensure ssh key is absent
  include_tasks: ssh-key-clear.yml
