---
- name: Ensure ssh key is present
  include_tasks: ssh-key-available.yml

- name: Remove existing file
  shell: |
    if [[ -e {{ ar_git_repo_item | dirname }} ]]
    then
      cd {{ ar_git_repo_item | dirname }}
      git rm $(basename {{ ar_git_repo_item }})
    fi
  args:
    removes: "{{ ar_git_repo_item }}"
  with_items: "{{ ar_git_repo_remove_list | flatten }}"
  loop_control:
    loop_var: ar_git_repo_item

- name: Commit and push changes
  include_tasks: checkin.yml
