---
# Clear the ssh key from the machine
- name: Remove the ssh key
  file:
    path: "{{ ar_git_repo_ssh_key_path }}"
    state: absent
  changed_when: false

- name: Clear ssh-agent
  shell: export SSH_AUTH_SOCK={{ ar_git_repo_ssh_agent_socket }}; ssh-add -D
  changed_when: false
  when: ar_git_repo_ssh_key_pass is defined and ar_git_repo_ssh_key_pass != ''
