---
- name: Ensure key directory is present
  file:
    path: "{{ ar_git_repo_ssh_key_path | dirname }}"
    mode: 0700
    state: directory

- name: Put the ssh key onto the file system
  copy:
    dest: "{{ ar_git_repo_ssh_key_path }}"
    content: "{{ ar_git_repo_ssh_key | b64decode }}\n"
    mode: 0600
  changed_when: false

- name: Include tasks to integrate ssh-agent
  include_tasks: ssh-agent.yml
  when: ar_git_repo_ssh_key_pass is defined and ar_git_repo_ssh_key_pass != ''

- name: Ensure ssh config is set
  template:
    src: sshconfig.j2
    dest: "{{ ar_git_repo_ssh_key_path | dirname }}/config"
    mode: 0600
  when: ar_git_repo_ssh_key_pass is not defined or ar_git_repo_ssh_key_pass == ''
