---
- name: Remove git repo from filesystem
  file:
    path: "{{ ar_git_repo_item.value }}"
    state: absent
  with_dict: "{{ ar_git_repo_paths }}"
  loop_control:
    loop_var: ar_git_repo_item
  changed_when: false
  listen: "cleanup"

- name: Reset vars
  set_fact:
    ar_git_repo_auto_cleanup: "{{ _ar_git_repo_auto_cleanup }}"
  listen: "cleanup"

- name: Remove ssh key
  include_tasks: ssh-key-clear.yml
  listen: "cleanup"
